<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>TermPaper</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\TermPaper.Application\TermPaper.Application.csproj" />
        <ProjectReference Include="..\TermPaper.Infrastructure\TermPaper.Infrastructure.csproj" />
    </ItemGroup>

</Project>